// frontend/src/content/components/fieldset/examples/small-legend.solid.tsx
import Fieldset from "@i-dot-ai-npm/component-library-solid/fieldset/Fieldset";
import FieldsetLegend from "@i-dot-ai-npm/component-library-solid/fieldset/FieldsetLegend";

export default function Example() {
  return (
    <Fieldset>
      <FieldsetLegend size="small">What is your address?</FieldsetLegend>
    </Fieldset>
  );
}

// frontend/src/content/components/fieldset/examples/small-legend.svelte
<script>
  import Fieldset from "@i-dot-ai-npm/component-library-svelte/fieldset/Fieldset.svelte";
  import FieldsetLegend from "@i-dot-ai-npm/component-library-svelte/fieldset/FieldsetLegend.svelte";
</script>

<Fieldset>
  <FieldsetLegend size="small">What is your address?</FieldsetLegend>
</Fieldset>
